# Generated by Django 3.2 on 2021-10-12 06:46

import django.contrib.postgres.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='heart_rate_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heart_rate_voltage', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='test_things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=8), size=1)),
                ('heart_rate_voltage', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
