# Generated by Django 3.2 on 2021-10-12 06:58

import django.contrib.postgres.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('heart_rate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPG_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=8), size=1)),
                ('heart_rate_voltage', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
